### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by kkayacan** [keremkoseoglu/ABAP-Library#2]
An index would be useful if you don't intend keep this repo only for personal use.

**Comment by keremkoseoglu** [comment]
My intention is:

- [ ] Creating subfolders; such as business objects, exception classes, etc.
- [ ] Writing an index file, indicating what's where

**Comment by keremkoseoglu** [comment]
@kkayacan I have split the project into subdirectories. But I didn't feel the urge to write an index file, since file names are pretty much intuitive. Therefore, I'm closing this issue.

I have the intention of writing a readme file - check #3  . That file may include a basic map.

If you disagree, you can reopen this issue. Cheers!
