### ISSUE TITLE
Problem when Pulling the Project to On-Premise SAP System

### ISSUE THREAD

**Issue by philip4sap** [keremkoseoglu/ABAP-Library#5]
When I try to pull the project to an onpremise SAP system , it is giving error 
'Current login language 'EN' does not match master language 'TR'. Run 'Advanced' > 'Open in master language' . When I go to the advanced settings and try to open in master langauge , it is throwing error 'Please install the abapGit repository'

**Comment by keremkoseoglu** [comment]
Dear @philip4sap , this is not a problem with my repository, but rather a bug regarding abapGit - and if you look deeper, an error generated by SAP itself.

This issue is mentioned on abapGit repository, and is closed, you can try your luck there: https://github.com/abapGit/abapGit/issues/1478

Same issue mentioned on ADT repository: https://github.com/abapGit/ADT_Backend/issues/5

Maybe this note may help you: https://launchpad.support.sap.com/#/notes/2200878
